import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/components/ui/Toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastProvider>
          {/* Global Header */}
          <header className="bg-surface border-b border-border">
            <div className="max-w-7xl mx-auto px-6 lg:px-8 py-5">
              <div className="flex items-center justify-between">
                <h1 className="text-sm font-semibold text-primary tracking-wide">SSII Inventory Management System</h1>
                <div className="flex items-center space-x-4">
                  <span className="text-sm text-muted">Welcome to your inventory dashboard</span>
                </div>
              </div>
            </div>
          </header>
          {children}
        </ToastProvider>
      </body>
    </html>
  );
}
